DROP TABLE FLIGHT_UNION;

CREATE TABLE FLIGHT_UNION
AS
select b."LATITUDE",
b."LONGITUDE",
b."AIRPORT_ID" as "FROM_AIRPORT_ID",
b."NAME" as "FROM_AIRPORT_NAME",
b."COUNTRY" as "FROM_AIRPORT_COUNTRY",
b."IATA" as "FROM_AIRPORT_IATA",
b."CITY" as "FROM_AIRPORT_CITY",
c."AIRLINE_ID",
c."AIRLINE_NAME",
c."AIRLINE_ALIAS",
c."IATA" as "AIRLINE_IATA",
d."AIRPORT_ID" as "TO_AIRPORT_ID",
d."NAME" as "TO_AIRPORT_NAME",
d."COUNTRY" as "TO_AIRPORT_COUNTRY",
d."IATA" as "TO_AIRPORT_IATA",
d."CITY" as "TO_AIRPORT_CITY"
from public."ROUTES" as a
LEFT JOIN public."AIRPORTS" as b on a."SOURCE_AIRPORT" = b."IATA"
LEFT JOIN public."AIRLINES" as c on c."AIRLINE_ID" = a."AIRLINE_ID"
LEFT JOIN public."AIRPORTS" as d on a."DESTINATION_AIRPORT" = d."IATA"
UNION ALL
select b."LATITUDE",
b."LONGITUDE",
b."AIRPORT_ID" as "FROM_AIRPORT_ID",
b."NAME" as "FROM_AIRPORT_NAME",
b."COUNTRY" as "FROM_AIRPORT_COUNTRY",
b."IATA" as "FROM_AIRPORT_IATA",
b."CITY" as "FROM_AIRPORT_CITY",
c."AIRLINE_ID",
c."AIRLINE_NAME",
c."AIRLINE_ALIAS",
c."IATA" as "AIRLINE_IATA",
d."AIRPORT_ID" as "TO_AIRPORT_ID",
d."NAME" as "TO_AIRPORT_NAME",
d."COUNTRY" as "TO_AIRPORT_COUNTRY",
d."IATA" as "TO_AIRPORT_IATA",
d."CITY" as "TO_AIRPORT_CITY"
from public."ROUTES" as a
LEFT JOIN public."AIRPORTS" as b on a."DESTINATION_AIRPORT" = b."IATA"
LEFT JOIN public."AIRLINES" as c on c."AIRLINE_ID" = a."AIRLINE_ID"
LEFT JOIN public."AIRPORTS" as d on a."SOURCE_AIRPORT" = d."IATA"